name: Researcher
description: Personal website
menu:
 - page: About
   url: /about
 - page: Papers
   url: /papers
   links:
    - title: Working papers
      url: "#working-papers"
    - title: Published papers
      url: "#published-papers"
 - page: Research Projects
   url: /research
   links:
    - title: Hydrogen's Value in the Energy System (HYVE)
      url: "http://www.hyve.org.uk/"
    - title: "Project Two"
      url: "#project-two"
    - title: "Project Three"
      url: "#project-three"
    - title: "Project Four"
      url: "#project-four"
 - page: Curriculum Vitae
   url: /cv
   links:
    - title: Experience
      url: "#experience"
    - title: Education
      url: "#education"
    - title: Positions
      url: "#positions"
    - title: Miscellaneous
      url: "#miscellaneous"
 - page: Teaching
   url: /teaching
 - page: Media
   url: /media
 - page: Accolades
   url: /accolades
menu_external:
 - title: randyweisun.com
   url: "https://www.eng.ed.ac.uk/about/people/mr-wei-sun"
 - title: Research Gate
   url: "https://www.researchgate.net/profile/Wei_Sun111"
 - title: LinkedIn
   url: "https://www.linkedin.com/feed/"
# - title: Twitter
#   url: "http://randyweisun.com/"
mathjax: false
markdown: kramdown
encoding: utf-8
baseurl: 
locale: en_GB